### ISSUE TITLE
Create/Improve  Landing Page (Home page)

### ISSUE THREAD

**Issue by purnima143** [anitab-org/anitab-org.github.io#161]
## PROBLEM
A website without landing page doesn't look like a website.
When the website loads, the front page looks like any documentation which has a long description of the organisation and their activities-no icons, no bullets. Even the chosen font is so thin, that's not the user friendly.
![image](https://user-images.githubusercontent.com/57852378/98330648-dc2e5b80-2020-11eb-8151-9ad89f6a3e75.png)
## TASK TO DO
- [ ] Create landing page wireframe using Figma/adobe

- [ ] Improve the design of the home page.

- [ ] Please take care of the colour scheme of the project.

**Comment by purnima143** [comment]
Can I work on this issue?

**Comment by Akanksha1212** [comment]
Hi @purnima143, The work on content is going on (https://github.com/anitab-org/anitab-org.github.io/issues/108) and for design and color scheme you can discuss it with design team on Zulip. Pls join [AnitaB zulip](https://anitab-org.zulipchat.com/) if you haven't.

**Comment by Akanksha1212** [comment]
Closing this issue as the work on these tasks is going on.
